--- #YAML:1.0
name:               Data-Iterator-Hierarchical
version:            0.07
abstract:           Iterate hierarchically over tabular data
author:
    - Brian McCauley <nobull@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
