--- #YAML:1.0
name:                Data-Iterator-Hierarchical
version:             0.04
abstract:            Iterate hierarchically over tabular data
license:             ~
author:              
    - Brian McCauley <nobull@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
